<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <IsTestProject>true</IsTestProject>
    <TestProjectType>UnitTest</TestProjectType>
    <IsPackable>false</IsPackable>
    <IsCodedUITest>False</IsCodedUITest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Analyzer.Testing" Version="1.1.4" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.6.0" />
    <PackageReference Include="MSTest" Version="4.1.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Elements.Quantity.DiagnosticAnalyzers\Elements.Quantity.DiagnosticAnalyzers.csproj" />
    <ProjectReference Include="..\Elements.Quantity\Elements.Quantity.csproj" />
  </ItemGroup>
</Project>
