name: Build Library

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  release:
    types: [published]

jobs:
  build:
    name: 'Build and publish library'
    runs-on: ubuntu-latest

    env:
      IS_RELEASE: ${{ github.event_name == 'release' && github.event.action == 'published' }}

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 'Build NuGet'
        uses: Yellow-Dog-Man/composite-actions-templates/.github/actions/dotnet-build@606ac289d701be7b7d90e5ff8647dedf57d6d755 # main
        with:
          dotnet-build-args: ${{ env.IS_RELEASE == 'true' && format('-p:Version={0} -o nupkgs', github.ref_name) || '-o nupkgs' }}
          dotnet-project-path: '.'
          dotnet-build-type: 'pack'

      - name: 'Upload artifacts'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: 'nupkgs/*'

      - name: 'Push NuGet'
        if: ${{ env.IS_RELEASE == 'true' }}
        uses: Yellow-Dog-Man/composite-actions-templates/.github/actions/dotnet-build-push-nuget@606ac289d701be7b7d90e5ff8647dedf57d6d755 # main
        with:
          dotnet-nuget-auth-token: ${{ secrets.NUGET_TOKEN }}
