name: Publish Library

# When a release is published
on:
  release:
    types: [published]
jobs:
  publish:
    # Windows Server 2022 contains .NET 9
    runs-on: windows-2022
    env:
      VERSION: ${{ github.event.release.tag_name }}
    steps:
    - uses: actions/checkout@v5
    - name: Get version
      run: echo "Building with ${{ env.VERSION }}"
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore -p:Version=${{ env.VERSION }}
    - name: Pack
      run: dotnet pack Elements.Quantity --output nupkgs --configuration Release -p:Version=${{ env.VERSION }}
    - name: Nuget Publish
      run: dotnet nuget push nupkgs\*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
