name: Test Library

on:
  workflow_dispatch:
  push:
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.props'
    branches:
      - main
  pull_request:
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.props'
    branches:
      - main

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Install Dependencies
        run: dotnet restore
      - name: Run Test
        run: dotnet test --configuration Release --no-restore --logger "trx;LogFileName=test-results.trx" || true
      - name: Generate Test Report
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: Elements.Quantity.Test
          path: '**/test-results.trx'
          reporter: dotnet-trx
          fail-on-error: true
